function createfigure(cdata1, XData1, YData1, cdata2, XData2, YData2, cdata3, XData3, YData3, cdata4, XData4, YData4, cdata5, XData5, YData5, cdata6, XData6, YData6, cdata7, XData7, YData7, cdata8, XData8, YData8, cdata9, XData9, YData9, cdata10, XData10, YData10, cdata11, XData11, YData11)
%CREATEFIGURE(CDATA1, XDATA1, YDATA1, CDATA2, XDATA2, YDATA2, CDATA3, XDATA3, YDATA3, CDATA4, XDATA4, YDATA4, CDATA5, XDATA5, YDATA5, CDATA6, XDATA6, YDATA6, CDATA7, XDATA7, YDATA7, CDATA8, XDATA8, YDATA8, CDATA9, XDATA9, YDATA9, CDATA10, XDATA10, YDATA10, CDATA11, XDATA11, YDATA11)
%  CDATA1:  image cdata
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  CDATA2:  image cdata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  CDATA3:  image cdata
%  XDATA3:  line xdata
%  YDATA3:  line ydata
%  CDATA4:  image cdata
%  XDATA4:  line xdata
%  YDATA4:  line ydata
%  CDATA5:  image cdata
%  XDATA5:  line xdata
%  YDATA5:  line ydata
%  CDATA6:  image cdata
%  XDATA6:  line xdata
%  YDATA6:  line ydata
%  CDATA7:  image cdata
%  XDATA7:  line xdata
%  YDATA7:  line ydata
%  CDATA8:  image cdata
%  XDATA8:  line xdata
%  YDATA8:  line ydata
%  CDATA9:  image cdata
%  XDATA9:  line xdata
%  YDATA9:  line ydata
%  CDATA10:  image cdata
%  XDATA10:  line xdata
%  YDATA10:  line ydata
%  CDATA11:  image cdata
%  XDATA11:  line xdata
%  YDATA11:  line ydata

%  Auto-generated by MATLAB on 16-Sep-2017 01:06:51

% Create figure
figure1 = figure('NumberTitle','off','Name','P300 Query (resto)');
colormap('gray');

% Create axes
axes1 = axes('Parent',figure1,'Position',[0 0.5 0.2 0.5]);
axis off
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Create line
line(XData1,YData1,'Parent',axes1,'Color',[0 1 0]);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 58.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 61.5]);
box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'CLim',[0 255],'DataAspectRatio',[1 1 1],'Layer','top','TickDir',...
    'out');
% Create axes
axes2 = axes('Parent',figure1,'Position',[0.2 0.5 0.2 0.5]);
axis off
hold(axes2,'on');

% Create image
image(cdata2,'Parent',axes2,'CDataMapping','scaled');

% Create line
line(XData2,YData2,'Parent',axes2,'Color',[0 1 0]);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0.5 58.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0.5 61.5]);
box(axes2,'on');
axis(axes2,'ij');
% Set the remaining axes properties
set(axes2,'CLim',[0 255],'DataAspectRatio',[1 1 1],'Layer','top','TickDir',...
    'out');
% Create axes
axes3 = axes('Parent',figure1,'Position',[0.4 0.5 0.2 0.5]);
axis off
hold(axes3,'on');

% Create image
image(cdata3,'Parent',axes3,'CDataMapping','scaled');

% Create line
line(XData3,YData3,'Parent',axes3,'Color',[0 1 0]);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0.5 58.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0.5 61.5]);
box(axes3,'on');
axis(axes3,'ij');
% Set the remaining axes properties
set(axes3,'CLim',[0 255],'DataAspectRatio',[1 1 1],'Layer','top','TickDir',...
    'out');
% Create axes
axes4 = axes('Parent',figure1,'Position',[0.6 0.5 0.2 0.5]);
axis off
hold(axes4,'on');

% Create image
image(cdata4,'Parent',axes4,'CDataMapping','scaled');

% Create line
line(XData4,YData4,'Parent',axes4,'Color',[0 1 0]);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[0.5 58.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[0.5 61.5]);
box(axes4,'on');
axis(axes4,'ij');
% Set the remaining axes properties
set(axes4,'CLim',[0 255],'DataAspectRatio',[1 1 1],'Layer','top','TickDir',...
    'out');
% Create axes
axes5 = axes('Parent',figure1,'Position',[0.8 0.5 0.2 0.5]);
axis off
hold(axes5,'on');

% Create image
image(cdata5,'Parent',axes5,'CDataMapping','scaled');

% Create line
line(XData5,YData5,'Parent',axes5,'Color',[0 1 0]);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes5,[0.5 58.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes5,[0.5 61.5]);
box(axes5,'on');
axis(axes5,'ij');
% Set the remaining axes properties
set(axes5,'CLim',[0 255],'DataAspectRatio',[1 1 1],'Layer','top','TickDir',...
    'out');
% Create axes
axes6 = axes('Parent',figure1,'Position',[0 0 0.2 0.5]);
axis off
hold(axes6,'on');

% Create image
image(cdata6,'Parent',axes6,'CDataMapping','scaled');

% Create line
line(XData6,YData6,'Parent',axes6,'Color',[0 1 0]);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes6,[0.5 58.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes6,[0.5 61.5]);
box(axes6,'on');
axis(axes6,'ij');
% Set the remaining axes properties
set(axes6,'CLim',[0 255],'DataAspectRatio',[1 1 1],'Layer','top','TickDir',...
    'out');
% Create axes
axes7 = axes('Parent',figure1,'Position',[0.2 0 0.2 0.5]);
axis off
hold(axes7,'on');

% Create image
image(cdata7,'Parent',axes7,'CDataMapping','scaled');

% Create line
line(XData7,YData7,'Parent',axes7,'Color',[0 1 0]);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes7,[0.5 58.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes7,[0.5 61.5]);
box(axes7,'on');
axis(axes7,'ij');
% Set the remaining axes properties
set(axes7,'CLim',[0 255],'DataAspectRatio',[1 1 1],'Layer','top','TickDir',...
    'out');
% Create axes
axes8 = axes('Parent',figure1,'Position',[0.4 0 0.2 0.5]);
axis off
hold(axes8,'on');

% Create image
image(cdata8,'Parent',axes8,'CDataMapping','scaled');

% Create line
line(XData8,YData8,'Parent',axes8,'Color',[0 1 0]);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes8,[0.5 58.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes8,[0.5 61.5]);
box(axes8,'on');
axis(axes8,'ij');
% Set the remaining axes properties
set(axes8,'CLim',[0 255],'DataAspectRatio',[1 1 1],'Layer','top','TickDir',...
    'out');
% Create axes
axes9 = axes('Parent',figure1,'Position',[0.6 0 0.2 0.5]);
axis off
hold(axes9,'on');

% Create image
image(cdata9,'Parent',axes9,'CDataMapping','scaled');

% Create line
line(XData9,YData9,'Parent',axes9,'Color',[0 1 0]);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes9,[0.5 58.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes9,[0.5 61.5]);
box(axes9,'on');
axis(axes9,'ij');
% Set the remaining axes properties
set(axes9,'CLim',[0 255],'DataAspectRatio',[1 1 1],'Layer','top','TickDir',...
    'out');
% Create axes
axes10 = axes('Parent',figure1,'Position',[0.8 0 0.2 0.5]);
axis off
hold(axes10,'on');

% Create image
image(cdata10,'Parent',axes10,'CDataMapping','scaled');

% Create line
line(XData10,YData10,'Parent',axes10,'Color',[0 1 0]);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes10,[0.5 58.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes10,[0.5 61.5]);
box(axes10,'on');
axis(axes10,'ij');
% Set the remaining axes properties
set(axes10,'CLim',[0 255],'DataAspectRatio',[1 1 1],'Layer','top','TickDir',...
    'out');
% Create axes
axes11 = axes('Parent',figure1,'Position',[0 -0.5 0.2 0.5]);
axis off
hold(axes11,'on');

% Create image
image(cdata11,'Parent',axes11,'CDataMapping','scaled');

% Create line
line(XData11,YData11,'Parent',axes11,'Color',[0 1 0]);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes11,[0.5 58.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes11,[0.5 61.5]);
box(axes11,'on');
axis(axes11,'ij');
% Set the remaining axes properties
set(axes11,'CLim',[0 255],'DataAspectRatio',[1 1 1],'Layer','top','TickDir',...
    'out');
